In [ ]:
6  * 10

60

In [ ]:
import pandas as pd
df = pd.read_csv('salaries_by_college_major.csv')
df.head()

     Undergraduate Major  ...     Group
0             Accounting  ...  Business
1  Aerospace Engineering  ...      STEM
2            Agriculture  ...  Business
3           Anthropology  ...      HASS
4           Architecture  ...  Business

[5 rows x 6 columns]

In [ ]:
df.shape

(51, 6)

In [ ]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [ ]:
df.isna()

    Undergraduate Major  ...  Group
0                 False  ...  False
1                 False  ...  False
2                 False  ...  False
3                 False  ...  False
4                 False  ...  False
5                 False  ...  False
6                 False  ...  False
7                 False  ...  False
8                 False  ...  False
9                 False  ...  False
10                False  ...  False
11                False  ...  False
12                False  ...  False
13                False  ...  False
14                False  ...  False
15                False  ...  False
16                False  ...  False
17                False  ...  False
18                False  ...  False
19                False  ...  False
20                False  ...  False
21                False  ...  False
22                False  ...  False
23                False  ...  False
24                False  ...  False
25                False  ...  False
26                False  ...  False
27                False  ...  False
28                False  ...  False
29                False  ...  False
30                False  ...  False
31                False  ...  False
32                False  ...  False
33                False  ...  False
34                False  ...  False
35                False  ...  False
36                False  ...  False
37                False  ...  False
38                False  ...  False
39                False  ...  False
40                False  ...  False
41                False  ...  False
42                False  ...  False
43                False  ...  False
44                False  ...  False
45                False  ...  False
46                False  ...  False
47                False  ...  False
48                False  ...  False
49                False  ...  False
50                False  ...   True

[51 rows x 6 columns]

In [ ]:
df.tail()

      Undergraduate Major  ...  Group
46             Psychology  ...   HASS
47               Religion  ...   HASS
48              Sociology  ...   HASS
49                Spanish  ...   HASS
50  Source: PayScale Inc.  ...    NaN

[5 rows x 6 columns]

In [ ]:
clean_df = df.dropna()
clean_df.tail()

   Undergraduate Major  ...  Group
45   Political Science  ...   HASS
46          Psychology  ...   HASS
47            Religion  ...   HASS
48           Sociology  ...   HASS
49             Spanish  ...   HASS

[5 rows x 6 columns]

In [ ]:
clean_df['Starting Median Salary']

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [ ]:
clean_df['Starting Median Salary'].max()

74300.0

In [ ]:
clean_df['Starting Median Salary'].idmax()

AttributeError: ignored

In [ ]:
clean_df['Starting Median Salary'].idxmax()

43

In [ ]:
clean_df['Undergraduate Major'] [43]

'Physician Assistant'

In [ ]:
clean.df.loc[43]

NameError: ignored

In [ ]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [ ]:
print(clean_df['Mid-Career Median Salary'].max())
print(f"Index for the max mid career salary: {clean_df['Mid-Career Median Salary'].idxmax()}")
clean_df['Undergraduate Major'][8]

107000.0
Index for the max mid career salary: 8

'Chemical Engineering'

In [ ]:
print(clean_df['Starting Median Salary'].min())
clean_df['Undergraduate Major'].loc[clean_df['Starting Median Salary'].idxmin()]

34000.0

'Spanish'

In [ ]:
clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

In [ ]:
clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [ ]:
clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [ ]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

     Undergraduate Major    Spread  ...  Mid-Career 90th Percentile Salary     Group
0             Accounting  109800.0  ...                           152000.0  Business
1  Aerospace Engineering   96700.0  ...                           161000.0      STEM
2            Agriculture  113700.0  ...                           150000.0  Business
3           Anthropology  104200.0  ...                           138000.0      HASS
4           Architecture   85400.0  ...                           136000.0  Business

[5 rows x 7 columns]

In [ ]:
low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

In [ ]:
highest_potential = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_potential[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [ ]:
highest_spread = clean_df.sort_values('Spread', ascending=False)
highest_spread[['Undergraduate Major', 'Spread']].head()

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

In [ ]:
clean_df.groupby('Group').count()

          Undergraduate Major  ...  Mid-Career 90th Percentile Salary
Group                          ...
Business                   12  ...                                 12
HASS                       22  ...                                 22
STEM                       16  ...                                 16

[3 rows x 6 columns]

In [ ]:
clean_df.groupby('Group').mean()

                 Spread  ...  Mid-Career 90th Percentile Salary
Group                    ...
Business  103958.333333  ...                      147525.000000
HASS       95218.181818  ...                      129363.636364
STEM      101600.000000  ...                      157625.000000

[3 rows x 5 columns]

In [ ]:
pd.options.display.float_format = '{:,.2f}'.format

In [ ]:
pd.options.display.float_format = '{:,.2f}'.format
clean_df.groupby('Group').mean()

             Spread  ...  Mid-Career 90th Percentile Salary
Group                ...
Business 103,958.33  ...                         147,525.00
HASS      95,218.18  ...                         129,363.64
STEM     101,600.00  ...                         157,625.00

[3 rows x 5 columns]